---
- name: Install Docker
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        update_cache: yes
        state: present
    - name: Start docker daemon
      systemd:
        name: docker
        state: started

- name: Create new linux user
  hosts: all
  become: yes
  tasks:
    - name: Create new linux user
      user:
        name: julia
        groups: "{{user_groups}}"

- name: Install Docker-compose
  hosts: all
  tasks:
    - name: Create docker-compose directory
      file:
        path: ~/.docker/cli-plugins
        state: directory
    - name: Get architecture of remote machine
      shell: uname -m
      register: remote_arch
    - name: Install docker-compose
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-{{lookup('pipe', 'uname -m')}}"
        dest: ~/.docker/cli-plugins/docker-compose
        mode: +x

- name: Start docker containers
  hosts: all
  become: yes
  become_user: julia
  vars_files:
    - project-vars
  tasks:
    - name: Copy docker compose
      copy:
        src: /Users/juliadavydova/nana-projects/bootcamp-java-mysql-project/docker-compose-full.yaml
        dest: /home/julia/docker-compose.yaml

    - name: Docker login
      docker_login:
        username: "{{docker_username}}"
        password: "{{docker_password}}"

    - name: Start containers from compose
      community.docker.docker_compose_v2:
        project_src: /home/julia
