---
- name: Create Jenkins EC2
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create security group for Jenkins
      amazon.aws.ec2_security_group:
        name: jenkins-sg
        description: Security group for Jenkins
        region: eu-north-1
        vpc_id: vpc-054cf680083727d58
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: 0.0.0.0/0

          - proto: tcp
            ports:
              - 8080
            cidr_ip: 0.0.0.0/0
      register: jenkins_sg

    - name: Create EC2 instance
      amazon.aws.ec2_instance:
        name: "jenkins-server"
        key_name: "ansible-jenkins"
        instance_type: "t3.micro"
        image_id: "ami-0aba19e56f3eaec05"
        region: "eu-north-1"
        vpc_subnet_id: "subnet-0040a19a99d2c01ed"

        security_group: "{{ jenkins_sg.group_id }}"

        network:
          assign_public_ip: true

        wait: true
      register: ec2

    - name: Show EC2 result
      ansible.builtin.debug:
        msg: "{{ ec2.instances[0].public_ip_address }}"

    - name: Add Jenkins server to inventory
      ansible.builtin.add_host:
        name: "{{ ec2.instances[0].public_ip_address }}"
        groups: jenkins_server
        ansible_user: ubuntu
        ansible_ssh_private_key_file: "~/.ssh/ansible-jenkins.pem"

    - name: Wait for SSH
      ansible.builtin.wait_for:
        host: "{{ ec2.instances[0].public_ip_address }}"
        port: 22
        timeout: 300

- name: Configure Jenkins server
  hosts: jenkins_server
  become: true
  gather_facts: true

  tasks:
    - name: Install Jenkins on Ubuntu
      ansible.builtin.include_tasks: tasks/ubuntu.yaml
      when: ansible_facts["os_family"] == "Debian"

    - name: Install Jenkins on RedHat
      ansible.builtin.include_tasks: tasks/redhat.yaml
      when: ansible_facts["os_family"] == "RedHat"

    - name: Show detected OS family
      ansible.builtin.debug:
        msg: "OS family: {{ ansible_facts['os_family'] }}"

    - name: Run Jenkins in Docker
      ansible.builtin.include_tasks: tasks/jenkins-docker.yaml