---
- name: Create Jenkins EC2
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create security group for Jenkins
      amazon.aws.ec2_security_group:
        name: jenkins-sg
        description: Security group for Jenkins
        region: eu-north-1
        vpc_id: vpc-054cf680083727d58
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: 0.0.0.0/0

          - proto: tcp
            ports:
              - 8080
            cidr_ip: 0.0.0.0/0
      register: jenkins_sg

    - name: Create EC2 instance
      amazon.aws.ec2_instance:
        name: "jenkins-server"
        key_name: "ansible-jenkins"
        instance_type: "t3.micro"
        image_id: "ami-0aba19e56f3eaec05"
        region: "eu-north-1"
        vpc_subnet_id: "subnet-0040a19a99d2c01ed"

        security_group: "{{ jenkins_sg.group_id }}"

        network:
          assign_public_ip: true

        wait: true
      register: ec2

    - name: Show EC2 result
      ansible.builtin.debug:
        msg: "{{ ec2.instances[0].public_ip_address }}"

    - name: Add Jenkins server to inventory
      ansible.builtin.add_host:
        name: "{{ ec2.instances[0].public_ip_address }}"
        groups: jenkins_server
        ansible_user: ubuntu
        ansible_ssh_private_key_file: "~/.ssh/ansible-jenkins.pem"

    - name: Wait for SSH
      ansible.builtin.wait_for:
        host: "{{ ec2.instances[0].public_ip_address }}"
        port: 22
        timeout: 300

- name: Configure Jenkins server
  hosts: jenkins_server
  become: true

  tasks:
    - name: Test connection
      ansible.builtin.ping:

    - name: Install Java 21
      ansible.builtin.apt:
        name: openjdk-21-jre
        state: present
        update_cache: true

    - name: Download Jenkins repository key
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2026.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
        mode: "0644"

    - name: Add Jenkins repository
      ansible.builtin.deb822_repository:
        name: jenkins
        types:
          - deb
        uris:
          - https://pkg.jenkins.io/debian-stable
        suites:
          - binary/
        signed_by: /usr/share/keyrings/jenkins-keyring.asc
        state: present

    - name: Install Jenkins
      ansible.builtin.apt:
        name: jenkins
        state: present
        update_cache: true

    - name: Start and enable Jenkins
      ansible.builtin.service:
        name: jenkins
        state: started
        enabled: true

    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Start and enable Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Add Jenkins user to Docker group
      ansible.builtin.user:
        name: jenkins
        groups: docker
        append: true

    - name: Restart Jenkins
      ansible.builtin.service:
        name: jenkins
        state: restarted

    - name: Get Jenkins initial admin password
      ansible.builtin.slurp:
        src: /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password

    - name: Show Jenkins login information
      ansible.builtin.debug:
        msg:
          - "Jenkins URL: http://{{ inventory_hostname }}:8080"
          - "Password: {{ jenkins_password.content | b64decode }}"

