---
- name: Create Jenkins home volume
  community.docker.docker_volume:
    name: jenkins_home
    state: present

- name: Start Jenkins container
  community.docker.docker_container:
    name: jenkins
    image: jenkins/jenkins:lts
    state: started
    restart_policy: unless-stopped

    ports:
      - "8080:8080"
      - "50000:50000"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/bin/docker:/usr/bin/docker"
      - "jenkins_home:/var/jenkins_home"