---
- name: Install Java 21
  ansible.builtin.dnf:
    name: java-21-amazon-corretto
    state: present

- name: Add Jenkins repository
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins key
  ansible.builtin.rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2026.key

- name: Install Jenkins
  ansible.builtin.dnf:
    name: jenkins
    state: present

- name: Install Node.js
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: Install Docker
  ansible.builtin.dnf:
    name: docker
    state: present

- name: Start and enable Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add Jenkins user to Docker group
  ansible.builtin.user:
    name: jenkins
    groups: docker
    append: true

- name: Start and enable Jenkins
  ansible.builtin.service:
    name: jenkins
    state: started
    enabled: true