---
- name: Install Node.js and npm
  ansible.builtin.apt:
    name:
      - nodejs
      - npm
    state: present
    update_cache: true

- name: Install Docker
  ansible.builtin.apt:
    name: docker.io
    state: present

- name: Start and enable Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true